name: Docker Image CI - Leo

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicontagem:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicontagem:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicontagem:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicontagem
    - name: Azure login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  
    - name: Azure WebApp Container
      uses: Azure/webapps-container-deploy@v1
      with:
        # Name of the Azure Web App
        app-name: dmkmdkmskmsdm
        # Enter an existing Slot other than the Production slot
        images: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/apicontagem:latest
